name: Deploy to Docker Hub and EC2

on:
  push:
    branches:
      - main   # runs automatically on push to main
  workflow_dispatch: # also allow manual trigger

jobs:
  build:
    name: Build, Scan, and Push Docker Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Setup Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Log in to Docker Hub using token
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: shubheksam
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      # Build Docker image (load locally for Trivy scan)
      - name: Build Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: false
          load: true
          tags: shubheksam/prod-cn-website:latest

      # Scan image with Trivy
      - name: Scan image with Trivy
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: shubheksam/prod-cn-website:latest
          format: table
          exit-code: 1        # fail job if vulnerabilities found
          ignore-unfixed: true

      # Push Docker image (only runs if Trivy scan passed)
      - name: Push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: shubheksam/prod-cn-website:latest

  deploy:
    name: Deploy to EC2
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Save SSH key
        run: |
          echo "${{ secrets.SSHKEY }}" > prod-cn-website.pem
          chmod 600 prod-cn-website.pem

      - name: SSH into EC2 and deploy container
        run: |
          ssh -o StrictHostKeyChecking=no -i "prod-cn-website.pem" ubuntu@${{ secrets.EC2_HOST }} << 'EOF'
            # Login to Docker Hub
            echo "${{ secrets.DOCKER_HUB_TOKEN }}" | docker login -u "shubheksam" --password-stdin
          
            # Stop and remove old container
            docker stop prod-cn-website || true
            docker rm prod-cn-website || true
          
            # Pull latest image
            docker pull shubheksam/prod-cn-website:latest
          
            # Run new container (map port 8080 on host to port 80 in container)
            docker run -d --name prod-cn-website -p 8080:80 shubheksam/prod-cn-website:latest
          
            # Cleanup old images
            docker image prune -f
          EOF
